name: Build Android APK

on:
  push:
    branches: [ "main", "основной" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Unzip project code
      run: unzip wcsspoof-lsposed-module-3.zip -d ./extracted_project && mv ./extracted_project/*/* . || mv ./extracted_project/* . || true

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: lsposed-module-apk
        path: app/build/outputs/apk/release/app-release.apk
